import type { MealSlot, MealPlan, Meal, Recipe } from './meal'
import type { FavoriteRecord } from '../lib/firestoreSync'
import type {
  GroceryTagMap,
  PantryMap,
  GroceryEditMap,
  GroceryAdditionsMap,
  GroceryEdit,
} from './grocery'
import type { OnboardingState, UserProfile } from './profile'

// ─── Routing ──────────────────────────────────────────────────────────────────

export type AppRoute =
  | 'landing'
  | 'onboarding'
  | 'loading'
  | 'today'
  | 'dashboard'
  | 'recipe'
  | 'grocery'
  | 'nutrition'
  | 'favorites'

// ─── Meal overrides ───────────────────────────────────────────────────────────

// What the user has decided to do with a specific meal slot.
export type OverrideKind =
  | 'eating-out'  // skip entirely — not counted in nutrition or grocery
  | 'self-cook'   // user cooks their own recipe; name only, no ingredients
  | 'custom'      // swap in a known meal from the library
  | 'removed'     // leave the slot empty
  | 'default'     // restore original planned meal (clears an override)

export interface Override {
  kind: OverrideKind
  name?: string    // display name for self-cook and custom overrides
  mealId?: string  // library meal ID for custom overrides
}

// Keyed as `${dayIndex}_${slot}` so the whole week fits in one flat map.
export type OverrideMap = Record<string, Override>

// ─── Edit UI ──────────────────────────────────────────────────────────────────

// Set when the user taps "Edit / Swap" on a meal card; opens MealEditSheet.
export interface EditTarget {
  dayIndex: number
  slot: MealSlot
}

// ─── Auth ─────────────────────────────────────────────────────────────────────

// Static mock user — replaced by real auth in a future milestone.
export interface AppUser {
  name: string
  initial: string
  email: string
}

// ─── Full store state ─────────────────────────────────────────────────────────

// The complete shape exposed by StoreContext. Keeping it here (separate from
// the context file) lets utility functions and tests import just the type
// without pulling in React.
export interface StoreState {
  // Auth
  signedIn: boolean
  authLoading: boolean  // true until onAuthStateChanged fires for the first time
  user: AppUser
  authOpen: boolean
  setAuthOpen: (open: boolean) => void
  signIn: () => void
  signOut: () => void

  // Favorites
  favorites: Set<string>
  favoriteRecords: Map<string, FavoriteRecord>
  toggleFavorite: (mealId: string) => void

  // Meal overrides (manual edits to the generated plan)
  overrides: OverrideMap
  setOverride: (dayIndex: number, slot: MealSlot, value: Override | null) => void
  getOverride: (dayIndex: number, slot: MealSlot) => Override | null

  // Inline meal editing
  editTarget: EditTarget | null
  setEditTarget: (target: EditTarget | null) => void

  // Plan persistence
  planSaved: boolean
  setPlanSaved: (saved: boolean) => void
  planDirty: boolean   // true when overrides have changed since the last cloud save
  saveError: string | null

  // Grocery: store tags
  groceryTags: GroceryTagMap
  setGroceryTag: (itemName: string, tag: string | null) => void

  // Grocery: pantry stock adjustments
  pantryHave: PantryMap
  setHave: (itemName: string, amount: number) => void

  // Grocery: item edits (rename / requantify / remove)
  groceryEdits: GroceryEditMap
  setGroceryEdit: (originalName: string, edit: GroceryEdit | null) => void

  // Grocery: manually added items
  groceryAdditions: GroceryAdditionsMap
  addGroceryItem: (section: string, name: string, qty: string) => void
  removeGroceryAddition: (section: string, id: string) => void

  // Onboarding: raw form data persisted so re-entering the flow restores answers
  onboardingState: OnboardingState | null
  setOnboardingState: (s: OnboardingState) => void

  // Derived user profile (set when onboarding completes)
  profile: UserProfile | null
  setProfile: (p: UserProfile) => void

  // Recipe navigation: meal ID of the card the user tapped to open the recipe
  recipeTarget: string | null
  setRecipeTarget: (id: string | null) => void

  // Generated plan: set on onboarding completion; replaces the static PLAN fallback
  generatedPlan: MealPlan | null
  setGeneratedPlan: (plan: MealPlan) => void

  // AI generation state
  //   'gemini'           — successfully generated by Gemini via Firebase Function
  //   'sample'           — showing the static sample plan (signed-out or after Gemini error)
  //   'local-dev-fallback' — local generator used (dev / test only, not a normal user path)
  //   null               — no plan generated yet
  planSource: 'gemini' | 'sample' | 'local-dev-fallback' | null
  generationLoading: boolean
  generationError: string | null

  // Runtime meal/recipe/grocery data populated by a successful Gemini generation.
  // Empty for sample/local-dev-fallback plans, which use the static MEALS / RECIPE data.
  runtimeMeals:   Record<string, Meal>
  runtimeRecipes: Record<string, Recipe>
  runtimeGrocery: Array<{ section: string; name: string; qty: string }>

  // Unified meal lookup: runtimeMeals first, then static MEALS, then undefined.
  getMeal: (id: string) => Meal | undefined

  // Starts async Gemini plan generation. Callers (Onboarding) must gate on auth
  // before calling. Fire-and-forget — drives generationLoading / generationError /
  // generatedPlan state. Does NOT fall back to the local generator on failure.
  generatePlanAsync: (state: OnboardingState) => void

  // Switches to sample-plan mode: clears any generation error and shows the static plan.
  // Called from the Loading error screen "View sample plan" button.
  viewSamplePlan: () => void

  // Saves the current generated plan to Firestore. Called from Dashboard "Save plan" button.
  savePlanToCloud: () => void
}
